﻿services:
  app:
    container_name: nelitrabo-app
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Set the environment to Development for hot reload
      - DOTNET_USE_POLLING_FILE_WATCHER=1   # Enable file watching for hot reload
    volumes:
      - ./src:/src  # Mount the source code directory to allow hot reload
    command: ["dotnet", "watch", "run", "--no-launch-profile", "--urls", "http://+:5000;https://+:5001"]
  database:
    container_name: nelitrabo-db
    image: postgres:16
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h $$DB_HOST -p $$DB_PORT -U $$DB_USER -d $$DB_NAME"]
      interval: 30s
      retries: 5
      timeout: 10s

volumes:
  postgres_data:
    driver: local
