services:
  app:
    container_name: nelitrabo-app
    image: eb8.org/nelitrabo:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    container_name: nelitrabo-db
    image: postgres:16
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h $$DB_HOST -p $$DB_PORT -U $$DB_USER -d $$DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
