﻿﻿services:
  app:
    container_name: app
    image: eb8.org/nelitrabo:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    container_name: database
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h $$DB_HOST -p $$DB_PORT -U $$DB_USER -d $$DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
